import { Wrench } from "lucide-react";
import type { ComponentType } from "react";

export interface ToolMeta { slug: string; title: string; description: string; category: string; icon: ComponentType<{ className?: string }>; keywords: string[]; isPureFrontend: boolean; }

export const tools: ToolMeta[] = [
  { slug: "json-formatter", title: "JSON Formatter", description: "Format validate beautify JSON", category: "Developer", icon: Wrench, keywords: ["json formatter", "json beautifier", "json validator"], isPureFrontend: true },
  { slug: "base64-encoder", title: "Base64 Encoder/Decoder", description: "Encode decode Base64", category: "Developer", icon: Wrench, keywords: ["base64 encode", "base64 decode", "base64 encoder"], isPureFrontend: true },
  { slug: "url-encoder", title: "URL Encoder/Decoder", description: "URL encode decode", category: "Developer", icon: Wrench, keywords: ["url encode", "url decode", "url encoder"], isPureFrontend: true },
  { slug: "qr-code-generator", title: "QR Code Generator", description: "Generate QR codes", category: "Utility", icon: Wrench, keywords: ["qr code generator", "qr code maker"], isPureFrontend: true },
  { slug: "uuid-generator", title: "UUID Generator", description: "Generate random UUIDs", category: "Developer", icon: Wrench, keywords: ["uuid generator", "guid generator"], isPureFrontend: true },
  { slug: "password-generator", title: "Password Generator", description: "Generate secure passwords", category: "Utility", icon: Wrench, keywords: ["password generator", "random password"], isPureFrontend: true },
  { slug: "timestamp-converter", title: "Timestamp Converter", description: "Unix timestamp conversion", category: "Developer", icon: Wrench, keywords: ["timestamp converter", "unix timestamp"], isPureFrontend: true },
  { slug: "md5-generator", title: "MD5 SHA Hash Generator", description: "Generate hashes", category: "Developer", icon: Wrench, keywords: ["md5 generator", "sha256 generator"], isPureFrontend: true },
  { slug: "word-counter", title: "Word Counter", description: "Count words characters", category: "Text", icon: Wrench, keywords: ["word counter", "character count"], isPureFrontend: true },
  { slug: "color-converter", title: "Color Converter", description: "HEX RGB HSL conversion", category: "Design", icon: Wrench, keywords: ["color converter", "hex to rgb"], isPureFrontend: true },
  { slug: "text-to-slug", title: "Text to Slug", description: "URL slug generator", category: "Text", icon: Wrench, keywords: ["text to slug", "slug generator"], isPureFrontend: true },
  { slug: "html-entity-encoder", title: "HTML Entity Encoder/Decoder", description: "Encode decode HTML entities", category: "Developer", icon: Wrench, keywords: ["html entity encoder", "html entities"], isPureFrontend: true },
  { slug: "file-size-converter", title: "File Size Converter", description: "Convert file sizes", category: "Utility", icon: Wrench, keywords: ["file size converter", "bytes to mb"], isPureFrontend: true },
  { slug: "markdown-preview", title: "Markdown Preview", description: "Live Markdown preview", category: "Text", icon: Wrench, keywords: ["markdown preview", "markdown editor"], isPureFrontend: true },
  { slug: "image-compressor", title: "Image Compressor", description: "Compress images", category: "Image", icon: Wrench, keywords: ["image compressor", "compress image"], isPureFrontend: true },
  { slug: "css-minifier", title: "CSS Minifier", description: "Minify CSS code", category: "Developer", icon: Wrench, keywords: ["css minifier", "minify css", "css compressor"], isPureFrontend: true },
  { slug: "js-minifier", title: "JS Minifier", description: "Minify JavaScript", category: "Developer", icon: Wrench, keywords: ["js minifier", "minify js"], isPureFrontend: true },
  { slug: "html-minifier", title: "HTML Minifier", description: "Minify HTML", category: "Developer", icon: Wrench, keywords: ["html minifier", "minify html"], isPureFrontend: true },
  { slug: "json-to-yaml", title: "JSON to YAML", description: "Convert JSON to YAML", category: "Developer", icon: Wrench, keywords: ["json to yaml", "json yaml"], isPureFrontend: true },
  { slug: "yaml-to-json", title: "YAML to JSON", description: "Convert YAML to JSON", category: "Developer", icon: Wrench, keywords: ["yaml to json", "yaml json"], isPureFrontend: true },
  { slug: "csv-to-json", title: "CSV to JSON", description: "Convert CSV to JSON", category: "Developer", icon: Wrench, keywords: ["csv to json", "csv json"], isPureFrontend: true },
  { slug: "json-to-csv", title: "JSON to CSV", description: "Convert JSON to CSV", category: "Developer", icon: Wrench, keywords: ["json to csv", "json csv"], isPureFrontend: true },
  { slug: "xml-formatter", title: "XML Formatter", description: "Format XML", category: "Developer", icon: Wrench, keywords: ["xml formatter", "xml beautifier"], isPureFrontend: true },
  { slug: "lorem-ipsum", title: "Lorem Ipsum Generator", description: "Generate placeholder text", category: "Developer", icon: Wrench, keywords: ["lorem ipsum", "placeholder text"], isPureFrontend: true },
  { slug: "number-base-converter", title: "Number Base Converter", description: "Binary octal decimal hex", category: "Developer", icon: Wrench, keywords: ["number base converter", "binary decimal"], isPureFrontend: true },
  { slug: "regex-tester", title: "Regex Tester", description: "Test regular expressions", category: "Developer", icon: Wrench, keywords: ["regex tester", "regex test"], isPureFrontend: true },
  { slug: "sql-formatter", title: "SQL Formatter", description: "Format SQL", category: "Developer", icon: Wrench, keywords: ["sql formatter", "sql beautifier"], isPureFrontend: true },
  { slug: "jwt-decoder", title: "JWT Decoder", description: "Decode JWT tokens", category: "Developer", icon: Wrench, keywords: ["jwt decoder", "jwt parser"], isPureFrontend: true },
  { slug: "diff-checker", title: "Diff Checker", description: "Compare text", category: "Developer", icon: Wrench, keywords: ["diff checker", "text diff"], isPureFrontend: true },
  { slug: "text-case-converter", title: "Text Case Converter", description: "Change text case", category: "Text", icon: Wrench, keywords: ["text case converter", "case converter"], isPureFrontend: true },
  { slug: "text-sorter", title: "Text Sorter", description: "Sort text lines", category: "Text", icon: Wrench, keywords: ["text sorter", "sort text"], isPureFrontend: true },
  { slug: "text-reverse", title: "Text Reverser", description: "Reverse text", category: "Text", icon: Wrench, keywords: ["text reverse", "reverse text"], isPureFrontend: true },
  { slug: "duplicate-line-remover", title: "Duplicate Line Remover", description: "Remove duplicate lines", category: "Text", icon: Wrench, keywords: ["duplicate line remover", "remove duplicates"], isPureFrontend: true },
  { slug: "line-number-adder", title: "Line Number Adder", description: "Add line numbers", category: "Text", icon: Wrench, keywords: ["line number adder", "number lines"], isPureFrontend: true },
  { slug: "random-string", title: "Random String Generator", description: "Generate random strings", category: "Text", icon: Wrench, keywords: ["random string generator"], isPureFrontend: true },
  { slug: "list-randomizer", title: "List Randomizer", description: "Randomize list order", category: "Text", icon: Wrench, keywords: ["list randomizer", "shuffle list"], isPureFrontend: true },
  { slug: "text-trimmer", title: "Text Trimmer", description: "Trim whitespace", category: "Text", icon: Wrench, keywords: ["text trimmer", "trim text"], isPureFrontend: true },
  { slug: "letter-counter", title: "Letter Counter", description: "Count letter frequency", category: "Text", icon: Wrench, keywords: ["letter counter", "character frequency"], isPureFrontend: true },
  { slug: "morse-code", title: "Morse Code Translator", description: "Translate morse code", category: "Text", icon: Wrench, keywords: ["morse code", "morse code translator"], isPureFrontend: true },
  { slug: "palindrome-checker", title: "Palindrome Checker", description: "Check palindromes", category: "Text", icon: Wrench, keywords: ["palindrome checker", "palindrome test"], isPureFrontend: true },
  { slug: "text-repeater", title: "Text Repeater", description: "Repeat text", category: "Text", icon: Wrench, keywords: ["text repeater", "repeat text"], isPureFrontend: true },
  { slug: "list-sorter", title: "List Sorter", description: "Sort lists", category: "Text", icon: Wrench, keywords: ["list sorter", "sort list"], isPureFrontend: true },
  { slug: "length-converter", title: "Length Converter", description: "Convert length units", category: "Converter", icon: Wrench, keywords: ["length converter", "meter to feet"], isPureFrontend: true },
  { slug: "weight-converter", title: "Weight Converter", description: "Convert weight", category: "Converter", icon: Wrench, keywords: ["weight converter", "kg to lbs"], isPureFrontend: true },
  { slug: "temperature-converter", title: "Temperature Converter", description: "Convert temperature", category: "Converter", icon: Wrench, keywords: ["temperature converter", "celsius fahrenheit"], isPureFrontend: true },
  { slug: "speed-converter", title: "Speed Converter", description: "Convert speed", category: "Converter", icon: Wrench, keywords: ["speed converter", "kmh to mph"], isPureFrontend: true },
  { slug: "area-converter", title: "Area Converter", description: "Convert area", category: "Converter", icon: Wrench, keywords: ["area converter", "sq meters feet"], isPureFrontend: true },
  { slug: "volume-converter", title: "Volume Converter", description: "Convert volume", category: "Converter", icon: Wrench, keywords: ["volume converter", "liter gallon"], isPureFrontend: true },
  { slug: "time-converter", title: "Time Converter", description: "Convert time", category: "Converter", icon: Wrench, keywords: ["time converter", "seconds minutes"], isPureFrontend: true },
  { slug: "data-storage-converter", title: "Data Storage Converter", description: "Convert data", category: "Converter", icon: Wrench, keywords: ["data storage converter", "bytes gb"], isPureFrontend: true },
  { slug: "percentage-calculator", title: "Percentage Calculator", description: "Calculate percentages", category: "Calculator", icon: Wrench, keywords: ["percentage calculator", "percent calculator"], isPureFrontend: true },
  { slug: "discount-calculator", title: "Discount Calculator", description: "Calculate discounts", category: "Calculator", icon: Wrench, keywords: ["discount calculator", "sale price"], isPureFrontend: true },
  { slug: "tip-calculator", title: "Tip Calculator", description: "Calculate tips", category: "Calculator", icon: Wrench, keywords: ["tip calculator", "restaurant tip"], isPureFrontend: true },
  { slug: "age-calculator", title: "Age Calculator", description: "Calculate age", category: "Calculator", icon: Wrench, keywords: ["age calculator", "calculate age"], isPureFrontend: true },
  { slug: "date-difference", title: "Date Difference Calculator", description: "Days between dates", category: "Calculator", icon: Wrench, keywords: ["date difference", "days between dates"], isPureFrontend: true },
  { slug: "days-until", title: "Days Until Calculator", description: "Countdown to dates", category: "Calculator", icon: Wrench, keywords: ["days until", "countdown"], isPureFrontend: true },
  { slug: "bmi-calculator", title: "BMI Calculator", description: "Body Mass Index", category: "Calculator", icon: Wrench, keywords: ["bmi calculator", "body mass index"], isPureFrontend: true },
  { slug: "random-number", title: "Random Number Generator", description: "Generate random numbers", category: "Calculator", icon: Wrench, keywords: ["random number generator"], isPureFrontend: true },
  { slug: "dice-roller", title: "Dice Roller", description: "Roll virtual dice", category: "Calculator", icon: Wrench, keywords: ["dice roller", "roll dice"], isPureFrontend: true },
  { slug: "loan-calculator", title: "Loan Calculator", description: "Calculate loans", category: "Calculator", icon: Wrench, keywords: ["loan calculator", "mortgage calculator"], isPureFrontend: true },
  { slug: "gradient-generator", title: "CSS Gradient Generator", description: "Create CSS gradients", category: "Design", icon: Wrench, keywords: ["gradient generator", "css gradient"], isPureFrontend: true },
  { slug: "box-shadow-generator", title: "Box Shadow Generator", description: "Generate box shadows", category: "Design", icon: Wrench, keywords: ["box shadow generator", "css shadow"], isPureFrontend: true },
  { slug: "border-radius-generator", title: "Border Radius Generator", description: "Generate border radius", category: "Design", icon: Wrench, keywords: ["border radius generator", "css border radius"], isPureFrontend: true },
  { slug: "color-palette", title: "Color Palette Generator", description: "Generate color palettes", category: "Design", icon: Wrench, keywords: ["color palette", "color scheme"], isPureFrontend: true },
  { slug: "placeholder-image", title: "Placeholder Image Generator", description: "Generate placeholder images", category: "Design", icon: Wrench, keywords: ["placeholder image", "dummy image"], isPureFrontend: true },
  { slug: "emoji-picker", title: "Emoji Picker", description: "Browse copy emojis", category: "Design", icon: Wrench, keywords: ["emoji picker", "copy emoji"], isPureFrontend: true },
  { slug: "text-shadow-generator", title: "Text Shadow Generator", description: "CSS text shadow", category: "Design", icon: Wrench, keywords: ["text shadow generator", "css text shadow"], isPureFrontend: true },
  { slug: "contrast-checker", title: "Contrast Checker", description: "WCAG contrast check", category: "Design", icon: Wrench, keywords: ["contrast checker", "color contrast"], isPureFrontend: true },
  { slug: "favicon-generator", title: "Favicon Generator", description: "Generate favicons", category: "Design", icon: Wrench, keywords: ["favicon generator", "favicon creator"], isPureFrontend: true },
  { slug: "email-validator", title: "Email Validator", description: "Validate email addresses", category: "Web", icon: Wrench, keywords: ["email validator", "email checker"], isPureFrontend: true },
  { slug: "url-parser", title: "URL Parser", description: "Parse URL components", category: "Web", icon: Wrench, keywords: ["url parser", "parse url"], isPureFrontend: true },
  { slug: "meta-tag-generator", title: "Meta Tag Generator", description: "Generate SEO meta tags", category: "Web", icon: Wrench, keywords: ["meta tag generator", "seo meta tags"], isPureFrontend: true },
  { slug: "user-agent-parser", title: "User Agent Parser", description: "Parse user agent", category: "Web", icon: Wrench, keywords: ["user agent parser", "browser parser"], isPureFrontend: true },
  { slug: "http-status", title: "HTTP Status Reference", description: "HTTP status codes", category: "Web", icon: Wrench, keywords: ["http status codes", "status code"], isPureFrontend: true },
  { slug: "youtube-thumbnail", title: "YouTube Thumbnail Downloader", description: "Download YT thumbnails", category: "Web", icon: Wrench, keywords: ["youtube thumbnail", "yt thumbnail"], isPureFrontend: true },
  { slug: "open-graph-generator", title: "Open Graph Generator", description: "Generate OG tags", category: "Web", icon: Wrench, keywords: ["open graph generator", "og tags"], isPureFrontend: true },
  { slug: "ip-lookup", title: "IP Address Lookup", description: "Look up IP info", category: "Web", icon: Wrench, keywords: ["ip lookup", "what is my ip"], isPureFrontend: true },
  { slug: "stopwatch", title: "Online Stopwatch", description: "Stopwatch timer", category: "Utility", icon: Wrench, keywords: ["stopwatch", "online stopwatch", "timer"], isPureFrontend: true },
  { slug: "world-clock", title: "World Clock", description: "Check world times", category: "Utility", icon: Wrench, keywords: ["world clock", "time zones", "world time"], isPureFrontend: true },
  { slug: "coin-flip", title: "Coin Flip Simulator", description: "Flip a coin", category: "Utility", icon: Wrench, keywords: ["coin flip", "flip a coin", "heads tails"], isPureFrontend: true },
  { slug: "caesar-cipher", title: "Caesar Cipher", description: "Encrypt decrypt", category: "Utility", icon: Wrench, keywords: ["caesar cipher", "caesar cipher decoder"], isPureFrontend: true },
  { slug: "rot13-encoder", title: "ROT13 Encoder", description: "ROT13 encode decode", category: "Utility", icon: Wrench, keywords: ["rot13 encoder", "rot13 decoder"], isPureFrontend: true },
  { slug: "binary-text", title: "Binary to Text", description: "Binary text conversion", category: "Utility", icon: Wrench, keywords: ["binary to text", "text to binary"], isPureFrontend: true },
  { slug: "hex-text", title: "Hex to Text", description: "Hex text conversion", category: "Utility", icon: Wrench, keywords: ["hex to text", "text to hex"], isPureFrontend: true },
  { slug: "pomodoro-timer", title: "Pomodoro Timer", description: "Productivity timer", category: "Utility", icon: Wrench, keywords: ["pomodoro timer", "focus timer"], isPureFrontend: true },
  { slug: "roman-numerals", title: "Roman Numeral Converter", description: "Convert roman numerals", category: "Math", icon: Wrench, keywords: ["roman numerals", "roman numeral converter"], isPureFrontend: true },
  { slug: "prime-checker", title: "Prime Number Checker", description: "Check prime numbers", category: "Math", icon: Wrench, keywords: ["prime checker", "prime number"], isPureFrontend: true },
  { slug: "factorial-calculator", title: "Factorial Calculator", description: "Calculate factorials", category: "Math", icon: Wrench, keywords: ["factorial calculator", "n factorial"], isPureFrontend: true },
  { slug: "scientific-notation", title: "Scientific Notation Converter", description: "Convert scientific notation", category: "Math", icon: Wrench, keywords: ["scientific notation", "e notation"], isPureFrontend: true },
  { slug: "decimal-fraction", title: "Decimal to Fraction", description: "Convert decimals to fractions", category: "Math", icon: Wrench, keywords: ["decimal to fraction", "fraction calculator"], isPureFrontend: true },
  { slug: "gcf-calculator", title: "GCF LCM Calculator", description: "Greatest Common Factor", category: "Math", icon: Wrench, keywords: ["gcf calculator", "lcm calculator"], isPureFrontend: true },
  { slug: "image-to-base64", title: "Image to Base64", description: "Convert images to Base64", category: "Image", icon: Wrench, keywords: ["image to base64", "base64 image"], isPureFrontend: true },
];

export const categories = Array.from(new Set(tools.map(function(t){return t.category})));

export function getTool(slug: string) { return tools.find(function(t){return t.slug === slug}); }
